[alembic]
script_location = alembic
# this is the path to the migration scripts

[loggers]
keys = root, sqlalchemysqla

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemysqla]
level = WARN
handlers = console
qualname = sqlalchemysqla
propagate = 0

[handler_console]
class = StreamHandler
args = []
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s - %(levelname)s - %(message)s

[alembic:database]
url = driver://user:pass@localhost/dbname
# Update this line with your database connection URL
