"""add_approval_workflow_and_moderation_columns

Revision ID: 84d4c9e1715c
Revises: 31ef769171d9
Create Date: 2026-05-08 15:45:08.550456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d4c9e1715c'
down_revision: Union[str, Sequence[str], None] = '31ef769171d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type for project approval status
    project_approval_status = sa.Enum('pending', 'approved', 'rejected', name='projectapprovalstatus')
    project_approval_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('events', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='projectapprovalstatus'), server_default='pending', nullable=False))
    op.add_column('projects', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_featured')
    op.drop_column('projects', 'rejection_reason')
    op.drop_column('projects', 'approval_status')
    op.drop_column('events', 'is_published')
    op.drop_column('comments', 'is_hidden')
    # ### end Alembic commands ###

    # Drop enum type
    project_approval_status = sa.Enum('pending', 'approved', 'rejected', name='projectapprovalstatus')
    project_approval_status.drop(op.get_bind())
