"""add attendee column and event delete cascade to speaker relationship

Revision ID: 9138ab93e79b
Revises: ea57bed749ad
Create Date: 2026-01-17 13:41:47.260963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9138ab93e79b'
down_revision: Union[str, Sequence[str], None] = 'ea57bed749ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attendees')
    # ### end Alembic commands ###
